rottenGrapes/rottenApples/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    MovieList,
    MovieDetail,
    MovieCreation,
    MovieUpdate,
    MovieDelete
)

urlpatterns = [

    url(r'^$', MovieList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', MovieDetail.as_view(), name='detail'),
    url(r'^new$', MovieCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', MovieUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', MovieDelete.as_view(), name='delete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rottenGrapes/rottenGrapes/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('rottenApples.urls', namespace='movies')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rottenGrapes/rottenApples/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

GENRES_CHOICES = (("Action","Action"),("Comedy","Comedy"),("Drama","Drama"), ("Horror","Horror"),("Romance","Romance"),)
CLASSIFICATIONS = (("PG-13","PG-13"),("G","G"),("R","R"),)

# Create your models here.
class Movie(models.Model):
	name = models.CharField(max_length=250)
	year_of_release= models.IntegerField(editable=False)
	image = models.ImageField(upload_to='movie/pictures')
	release_date = models.DateField()
	classification = models.CharField(max_length=250, choices=CLASSIFICATIONS)
	genre = models.CharField(max_length=250, choices=GENRES_CHOICES)
	duration = models.IntegerField()

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.year_of_release = self.release_date.year
		super(Movie,self).save(*args, **kwargs)

class Review(models.Model):
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
	star_rating = models.IntegerField(null=False, validators = [MaxValueValidator(5),MinValueValidator(0)])
	user = models.ForeignKey(User)
	comment = models.CharField(max_length=250)

	def __str__(self):
		return u'%s stars - %s' % (self.star_rating,self.user)

rottenGrapes/rottenApples/forms.py
from django import forms
from .models import *

class DateInput(forms.DateInput):
	input_type = 'date'

class MovieForm(forms.ModelForm):
	class Meta:
		model = Movie
		fields = '__all__'
		widgets = {
			'release_date': DateInput()
		}

rottenGrapes/rottenApples/views.py
# # -*- coding: utf-8 -*-
# from __future__ import unicode_literals

# from django.shortcuts import render

# # Create your views here.
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView,UpdateView,DeleteView)
from django.core.urlresolvers import reverse_lazy
from .models import Movie
from .forms import MovieForm

# class MyView(View)
# 	def get(self,request)
# 		return HttpResponse('result')

class MovieList(ListView):
	template_name = 'movies/movie_list.html'
	model = Movie
	paginate_by = 10
	ordering = ['-year_of_release']

class MovieDetail(DetailView):
	template_name = 'movies/movie_detail.html'
	model = Movie

class MovieCreation(CreateView):
	template_name = 'movies/movie_form.html'
	form_class = MovieForm
	model = Movie
	success_url = reverse_lazy('movies:list')
	queryset = Movie.objects.all()

	def form_valid(self,form):
		print(form.cleaned_data)
		return super().form_valid(form)

class MovieUpdate(UpdateView):
	model = Movie
	success_url = reverse_lazy('movies:list')
	fields = ['name','release_date','genre']

class MovieDelete(DeleteView):
	model = Movie
	success_url = reverse_lazy('movies:list')

rottenGrapes/templates/movies/movie_detail.html
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}" />
</head>

<details class='sumario'>
 <summary>Content</summary>
  <nav>
    <ol>
      <li><a href="#Name">Name</a></li>
      <li><a href="#Photo">Photo</a></li>
      <li><a href="#Year_of_Release">Year of Release</a></li>
      <li><a href="#Classification">Classification</a></li>
      <li><a href="#Release_Date">Release Date</a></li>
      <li><a href="#Genre">Genre</a></li>
      <li><a href="#Duration">Duration</a></li>
      <li><a href="#Return">Return</a>
    </ol>
  </nav>
</details>

<article>
<h2 id="Name">Name</h2>
<p>{{ movie.name}}</p>

<h2 id="Photo">Photo</h2>
<p>
	<img src="{{ movie.image.url }}" width="240px" />

</p>

<h2 id="Year_of_Release">Year of Release</h2>
<p>{{ movie.year_of_release}}</p>

<h2 id="Classification">Classification</h2>
<p>{{ movie.classification}}</p>

<h2 id="Release_Date">Release Date</h2>
<p> {{ movie.release_date}}</p>

<h2 id="Genre">Genre</h2>
<p>{{ movie.genre}}</p>

<h2 id="Duration">Duration</h2>
<p>{{ movie.duration}} min</p>

<h2 id="Return"> Return</h2>
<p>
    <a href="{% url "movies:list" %}">Return</a>
</p>
</article>

rottenGrapes/templates/movies/movie_form.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

{% load crispy_forms_tags %}

<div class="container">
	<form action="." method="post">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <input type="submit" value="Save" />
	</form>	
</div>

rottenGrapes/templates/movies/movie_list.html
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
</head>
<p>
    <a href="{% url "movies:new" %}">Agregar curso</a>
</p>

<div>
  <ul>
    {% for movie in object_list %}
        <li>
          <img src="{{ movie.image.url }}" width="240px" />
          <h2>{{movie.name}}</h3>
          <h3>Release Date: {{movie.release_date}}</h2>
          <h3>{{movie.classification}}</h4>
          <p>
              <a href="{% url "movies:detail" movie.id %}">Ver</a> | 
              <a href="{% url "movies:edit" movie.id %}">Editar</a> | 
              <a href="{% url "movies:delete" movie.id %}">Borrar</a> 
          </p>  
        </li>
    {% endfor %}
  </ul>
</div>    
<ul>
    {% for movie in object_list %}
        <li>
            
            
        </li>
    {% endfor %}
</ul>

rottenGrapes/templates/movies/movieconfirmdelete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>